=== hmrc/breathing-space-if-dynamic-stub/conf/schemas/PUT-Individual-Details-Request.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Schema of PUT Individual Details document request",
  "title": "Breathing Space Individual Documents",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "residencyList": {
      "$ref": "#/definitions/uk.gov.hmrc.breathingspaceifstub.model.ResidencyList"
    },
    "nameList": {
      "$ref": "#/definitions/uk.gov.hmrc.breathingspaceifstub.model.NameList"
    },
    "indicators": {
      "$ref": "#/definitions/uk.gov.hmrc.breathingspaceifstub.model.Indicators"
    },
    "details": {
      "$ref": "#/definitions/uk.gov.hmrc.breathingspaceifstub.model.Details"
    },
    "addressList": {
      "$ref": "#/definitions/uk.gov.hmrc.breathingspaceifstub.model.AddressList"
    }
  },
  "required": [
    "details"
  ],
  "definitions": {
    "uk.gov.hmrc.breathingspaceifstub.model.NameList": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "nameEndDate": {
                "type": "string",
                "format": "date"
              },
              "honours": {
                "type": "string"
              },
              "titleType": {
                "type": "integer"
              },
              "surname": {
                "type": "string"
              },
              "nameType": {
                "type": "integer"
              },
              "secondForename": {
                "type": "string"
              },
              "nameStartDate": {
                "type": "string",
                "format": "date"
              },
              "requestedName": {
                "type": "string"
              },
              "nameSequenceNumber": {
                "type": "integer"
              },
              "firstForename": {
                "type": "string"
              },
              "otherTitle": {
                "type": "string"
              }
            },
            "required": [

            ]
          }
        }
      },
      "required": [
        "name"
      ]
    },
    "uk.gov.hmrc.breathingspaceifstub.model.AddressList": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "address": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "addressLine1": {
                "type": "string"
              },
              "addressLastConfirmedDate": {
                "type": "string",
                "format": "date"
              },
              "addressPostcode": {
                "type": "string"
              },
              "deliveryInfo": {
                "type": "string"
              },
              "addressLine4": {
                "type": "string"
              },
              "addressEndDate": {
                "type": "string",
                "format": "date"
              },
              "addressStatus": {
                "type": "integer"
              },
              "vpaMail": {
                "type": "integer"
              },
              "addressLine3": {
                "type": "string"
              },
              "countryCode": {
                "type": "integer"
              },
              "addressLine2": {
                "type": "string"
              },
              "pafReference": {
                "type": "string"
              },
              "addressType": {
                "type": "integer"
              },
              "addressSource": {
                "type": "integer"
              },
              "addressSequenceNumber": {
                "type": "integer"
              },
              "addressLine5": {
                "type": "string"
              },
              "addressStartDate": {
                "type": "string",
                "format": "date"
              }
            },
            "required": [

            ]
          }
        }
      },
      "required": [
        "address"
      ]
    },
    "uk.gov.hmrc.breathingspaceifstub.model.Indicators": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "manualCodingReason": {
          "type": "integer"
        },
        "welshOutputInd": {
          "type": "integer"
        },
        "saLinkInd": {
          "type": "integer"
        },
        "manualCodingOther": {
          "type": "string"
        },
        "s128Ind": {
          "type": "integer"
        },
        "saStartYear": {
          "type": "string"
        },
        "p2ToAgentInd": {
          "type": "integer"
        },
        "audioOutputInd": {
          "type": "integer"
        },
        "saFinalYear": {
          "type": "string"
        },
        "manualCorrInd": {
          "type": "integer"
        },
        "digitalP2Ind": {
          "type": "integer"
        },
        "bankruptcyInd": {
          "type": "integer"
        },
        "additionalNotes": {
          "type": "string"
        },
        "bankruptcyFiledDate": {
          "type": "string",
          "format": "date"
        },
        "eeaCmnwthInd": {
          "type": "integer"
        },
        "manualCorrReason": {
          "type": "string"
        },
        "noATSInd": {
          "type": "integer"
        },
        "taxEqualBenInd": {
          "type": "integer"
        },
        "noRepaymentInd": {
          "type": "integer"
        },
        "specialistBusinessArea": {
          "type": "integer"
        },
        "brailleOutputInd": {
          "type": "integer"
        },
        "manualCodingInd": {
          "type": "integer"
        },
        "noAllowInd": {
          "type": "integer"
        },
        "largePrintOutputInd": {
          "type": "integer"
        },
        "digitallyExcludedInd": {
          "type": "integer"
        },
        "utr": {
          "type": "string"
        },
        "deceasedInd": {
          "type": "integer"
        }
      },
      "required": [

      ]
    },
    "uk.gov.hmrc.breathingspaceifstub.model.ResidencyList": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "residency": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "residencySequenceNumber": {
                "type": "integer"
              },
              "dateLeavingUK": {
                "type": "string",
                "format": "date"
              },
              "dateReturningUK": {
                "type": "string",
                "format": "date"
              },
              "residencyStatusFlag": {
                "type": "integer"
              }
            },
            "required": [

            ]
          }
        }
      },
      "required": [
        "residency"
      ]
    },
    "uk.gov.hmrc.breathingspaceifstub.model.Details": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "liveAgentInd": {
          "type": "integer"
        },
        "ninoSuffix": {
          "type": "string"
        },
        "nino": {
          "type": "string"
        },
        "mergeStatus": {
          "type": "integer"
        },
        "marriageStatusType": {
          "type": "integer"
        },
        "ntTaxCodeInd": {
          "type": "integer"
        },
        "currOptimisticLock": {
          "type": "integer"
        },
        "dateOfDeath": {
          "type": "string",
          "format": "date"
        },
        "dateOfBirth": {
          "type": "string",
          "format": "date"
        },
        "liveCapacitorInd": {
          "type": "integer"
        },
        "dateOfRegistration": {
          "type": "string",
          "format": "date"
        },
        "accountStatusType": {
          "type": "integer"
        },
        "sex": {
          "type": "string"
        },
        "dateOfEntry": {
          "type": "string",
          "format": "date"
        },
        "dateOfDeathStatus": {
          "type": "integer"
        },
        "permanentTSuffixCaseIndicator": {
          "type": "integer"
        },
        "crnIndicator": {
          "type": "integer"
        },
        "adultRegSerialNumber": {
          "type": "string"
        },
        "cesaAgentIdentifier": {
          "type": "string"
        },
        "dateOfBirthStatus": {
          "type": "integer"
        },
        "cesaAgentClientReference": {
          "type": "string"
        },
        "registrationType": {
          "type": "integer"
        }
      },
      "required": [

      ]
    }
  }
}

=== hmrc/breathing-space-if-dynamic-stub/conf/data/static/individuals/IndividualDetailsForBS.json
{
  "details": {
    "nino": "${nino}",
    "dateOfBirth": "1976-12-11"
  },
  "nameList": {
    "name": [
      {
        "firstForename": "John",
        "secondForename": "Cena",
        "surname": "Smith",
        "nameType": 1
      }
    ]
  },
  "addressList": {
    "address": [
      {
        "addressLine1": "88 TESTING ROAD",
        "addressLine2": "TESTTOWN",
        "addressLine3": "TESTREGION",
        "addressLine4": "TESTAREA",
        "addressLine5": "TESTSHIRE",
        "addressPostcode": "XX77 6YY",
        "countryCode": 1,
        "addressType": 1
      }
    ]
  },
  "residencyList": {
    "residency": [
      {
        "residencySequenceNumber": 1,
        "dateLeavingUK": "2002-11-10",
        "dateReturningUK": "2002-12-10",
        "residencyStatusFlag": 1
      }
    ]
  },
  "indicators": {
    "manualCodingInd": 1,
    "manualCodingReason": 1,
    "manualCodingOther": "mm",
    "manualCorrInd": 1,
    "manualCorrReason": "mm",
    "additionalNotes": "mm",
    "deceasedInd": 1,
    "s128Ind": 1,
    "noAllowInd": 1,
    "eeaCmnwthInd": 1,
    "noRepaymentInd": 1,
    "saLinkInd": 1,
    "noATSInd": 1,
    "taxEqualBenInd": 1,
    "p2ToAgentInd": 1,
    "digitallyExcludedInd": 1,
    "bankruptcyInd": 1,
    "bankruptcyFiledDate": "2002-11-10",
    "utr": "mm",
    "audioOutputInd": 1,
    "welshOutputInd": 1,
    "largePrintOutputInd": 1,
    "brailleOutputInd": 1,
    "specialistBusinessArea": 1,
    "saStartYear": "2010",
    "saFinalYear": "2010",
    "digitalP2Ind": 1
  }
}
